# Generated by Django 3.1.2 on 2020-10-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vlersim'),
    ]

    operations = [
        migrations.AddField(
            model_name='liber',
            name='vlersimi_avg',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
