# Generated by Django 3.1.2 on 2020-10-31 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_liber_vlersimi_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlersim',
            name='perdorues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlersimet', to=settings.AUTH_USER_MODEL),
        ),
    ]
