# Generated by Django 3.1.2 on 2020-10-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201101_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlersim',
            name='liber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlersimet', to='app.liber'),
        ),
    ]
