# Generated by Django 3.1.2 on 2020-11-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201101_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liber',
            name='vlersimi_avg',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
